version: "3"

services:
  client:
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - password-brain

  api:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - password-brain
    volumes:
      - ./server:/app/server
      - node_modules:/app/server/node_modules/

  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=password-brain
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "8080:5432"
    networks:
      - password-brain

networks:
  password-brain:
    driver: bridge

volumes:
  node_modules:
  data:
